server:
  port: 7000

spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    hikari:
      poolName: HikariPoolZZZ
      connectionTimeout: '20000'
      maximumPoolSize: '5'
    url: jdbc:postgresql://localhost:5432/postgres
    password: 12345
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: 'false'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: 'true'
logging:
  level:
    org.springframework.web: DEBUG
security:
  jwt:
    secret: "njvglqmqtvykpthiedmtdhkllklzqallgrmqpecazhoghnqxchmrzdbsyzabesxq"
google:
  places:
    api-key: "AIzaSyCacHbx6-aTCdb06KU4RHx4YP-nP6mhZi8"
rapid:
  key: "2cdd0c5b0cmsh792eb545d2a731ap16a2cfjsn8d2e1d447f12"
